### ISSUE TITLE
Upgrade Node version

### ISSUE THREAD

**Issue by hdimon** [jonsth131/npm-audit#28]
Hello, please look at warning from pipeline.

**Describe the bug**
Azure DevOps pipeline gives warning: Task 'Npm audit' version 1 (npm-audit@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by jonsth131** [comment]
Thanks for reporting, this should be fixed in the new version.
